# Generated by Django 2.1.3 on 2018-11-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField()),
                ('html_version', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('h1', models.IntegerField()),
                ('h2', models.IntegerField()),
                ('h3', models.IntegerField()),
                ('h4', models.IntegerField()),
                ('h5', models.IntegerField()),
                ('h6', models.IntegerField()),
                ('internal', models.IntegerField()),
                ('external', models.IntegerField()),
                ('inaccessible', models.IntegerField()),
                ('has_login_form', models.BooleanField()),
            ],
        ),
    ]
